[package]
name = "iced_debug"
description = "A pluggable API for debugging iced applications"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[features]
enable = ["dep:iced_beacon"]
hot = [
    "enable",
    "dep:serde",
    "dep:serde_json",
    "dep:subsecond",
    "dep:wasm-bindgen",
    "dep:web-sys",
]

[dependencies]
dioxus-devtools.workspace = true
iced_core.workspace = true
iced_futures.workspace = true
log.workspace = true
subsecond.optional = true
subsecond.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
iced_beacon.workspace = true
iced_beacon.optional = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
serde.workspace = true
serde.features = ["derive"]
serde.optional = true
serde_json.workspace = true
serde_json.optional = true
wasm-bindgen.workspace = true
wasm-bindgen.optional = true
web-sys.workspace = true
web-sys.features = ["CloseEvent", "Location", "MessageEvent", "WebSocket", "Window"]
web-sys.optional = true
